server:
  port: 8083
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true    
spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.interstander.com:51521:XE
    username: Gukbi
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
            client-id: 560924579732-hatigjjf2fq825jj9ouot56cd8lgnkn0.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook: # /oauth2/authorization/google 이 주소를 동작하게 한다.
            client-id: 929042915063860
            client-secret: f9afc17484b188f87671ca69a6953971
            scope:
              - email
              - public_profile

          naver:
            client-id: Z83HwN9nrVY14O8Nn7a0
            client-secret: ZAtXCABcxa
            scope:
              - name
              - email
            client-name: Naver # 클라이언트 네임은 구글 페이스북도 대문자로 시작하더라.
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8083/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json의 response 키값으로 리턴해줌.
    profiles:
      include: oauth
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #JPA가 사용하는 기본 넘버링 전략을 사용하지 않는다.
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
cos:
  key: cos1234